substitutions:
  devicename: opentherm
  upper_devicename: Opentherm

esphome:
  name: $devicename
  platform: ESP8266
  board: d1_mini

external_components:
  - source: components

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: "${devicename} Fallback"
    password: !secret esphome_fallback_password

captive_portal:
logger:
api:
ota:

opentherm:
  in_pin: D5
  out_pin: D6

climate:
  - platform: opentherm
    hotwater:
      id: hot_water
      name: 'Hot water'

sensor:
  - platform: opentherm
